version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
  backend:
    build: ./server
    ports:
      - "5000:5000"
  db:
    image: mongo # Or PostgreSQL for SQL
    ports:
      - "27017:27017"
